variable "build_name" {
  description = "The name of the build."
  type        = string
  default     = "ubuntu"
}

variable "node" {
  description = "The node in the Proxmox cluster to create the template."
  type        = string
}

variable "vm_id" {
  description = "The ID used to reference the virtual machine. This will also be the ID of the final template. If not given, the next free ID on the node will be used."
  type        = number
}

variable "vm_name" {
  description = "Name of the virtual machine during creation. If not given, a isotime will be used."
  type        = string
}

variable "pool" {
  description = "Name of resource pool to create virtual machine in."
  type        = string
  default     = "Template"
}

variable "template_description" {
  description = "Description of the template, visible in the Proxmox interface."
  type        = string
  default     = "Template generated by Packer on {{ formatdate('YYYY-MM-DD hh:mm', timestamp()) }}."
}
