variable "node" {
  description = "The node in the Proxmox cluster to create the template."
  type        = string
}

variable "vm_id" {
  description = "The ID used to reference the virtual machine. This will also be the ID of the final template. If not given, the next free ID on the node will be used."
  type        = number
  default     = 0

  validation {
    condition     = (var.vm_id == 0) ? true : (var.vm_id >= 100 && var.vm_id <= 999999999)
    error_message = "The vm_id must be between 100 and 999999999 if specified."
  }
}

variable "vm_name" {
  description = "Name of the virtual machine during creation. If not given, Packer will generate a random name."
  type        = string
}

variable "pool" {
  description = "Name of resource pool to create virtual machine in."
  type        = string
  default     = "Template"
}

variable "template_description" {
  description = "Description of the template, visible in the Proxmox interface."
  type        = string
  default     = "Template generated by Packer on {{ isotime `2006-01-02 15:04` }}."
}
